name: build

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  build:
    name: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: Setup SDL3
        uses: libsdl-org/setup-sdl@main
        id: sdl
        with:
          install-linux-dependencies: true
          version: 3-latest
          version-sdl-image: 3-latest

      - name: Cache CMake deps
        uses: actions/cache@v5
        with:
          path: |
            build/_deps
            ~/.cache/CMake
          key: ${{ runner.os }}-cmake-${{ hashFiles('CMakeLists.txt', 'cmake/**/*.cmake', '.github/workflows/*.yml') }}
          restore-keys: |
            ${{ runner.os }}-cmake-

      - name: Configure
        run: cmake -S . -B build -DNEMU_ENABLE_TESTS=OFF

      - name: Build
        run: cmake --build build