name: build

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  build:
    name: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: Configure
        run: cmake -S . -B build -DNEMU_ENABLE_TESTS=OFF

      - name: Build
        run: cmake --build build